# Generated by Django 2.0.4 on 2018-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=300)),
                ('FeedBack', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
